version: 0.9.{build}
image: Visual Studio 2017
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  publish_aspnet_core: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 33iSDCwU3hJiKGPLq6Vv6lrZnJcDfdGBhvuGh9FlIwQjqAKRkG2gtxt0FWf4n5Dg