version: 1.2.{build}
image: Visual Studio 2017
before_build:
- ps: dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  publish_aspnet_core: true
  verbosity: minimal
test: off
deploy:
- provider: NuGet
  api_key:
    secure: LBITkcScbPgP5WftIqwRGBWqq3hu1pmqNPPqLtl389roRodJ9nobmv81egohgKej
  on:
    APPVEYOR_REPO_TAG: true